app:
  schema_file_name: 'schema.rb'
  seed_folder_path: <%= "#{RootService::PATH}/db/seeds" %>
  migrations_folder_path: <%= "#{RootService::PATH}/db/migrations" %>
  db_schema_folder_path: <%= "#{RootService::PATH}/db" %>
rabbitmq:
  consumer_pool: 10
db:
  adapter: postgresql
  host: localhost
  user: postgres
  password: password
  port: 5432
pagination:
  page_size: 10
secrets:
  secret_key_base:
