app:
  name: 'auth'
  schema_file_name: 'schema.rb'
  seed_folder_path: <%= "#{RootService::PATH}/db/seeds" %>
  migrations_folder_path: <%= "#{RootService::PATH}/db/migrations" %>
  db_schema_folder_path: <%= "#{RootService::PATH}/db" %>
rabbitmq:
  host: <%= ENV['RABBITMQ_HOST'] %>
  username: <%= ENV['RABBITMQ_USER'] %>
  password: <%= ENV['RABBITMQ_PASSWORD']%>
  consumer_pool: 10
logger:
  path: log/app.log
  level: info
db:
  adapter: postgresql
  host: localhost
  user: postgres
  password: password
  port: 5432
  url: <%= ENV['AUTH_DATABASE_URL'] %>
pagination:
  page_size: 10
secrets:
  secret_key_base:
